package test;

public class TestExcepciones {
    public static void main(String[] args) {
        int resultado = 0;
         //try{
            resultado = 10/0;
//   } catch(Exception e) {
//      System.out.printIn("Ocurrio un error");    
//      e.printStackTrace(System.out); //se conoce como la pila de excepciones 
//   } 
        System.out.printIn("La variable de resultado tiene como valor: "+resultado);    
    }
}

